# Site settings
title: 未来学校 - 中国第一所面向未来的学校
email: lili@seiue.com
description: 中国第一所面向未来的学校 高中是高级中学（high school）的简称，我国中学分为初级中学与高级中学，属于中等教育的范畴。高中是我国九年义务教育结束后更高等的教育机构，上承初中，下启大学，一般为三年制。中国的高中教育指初中以后高中阶段的教育， 包括：普通高中、职业高中、中等专业学校、技工学校等，均属于高中教育的范畴。
baseurl: ""
url: ""

# Build settings
markdown: kramdown

collections:
  courses:
    output: true

gems:
  - jekyll-babel
